const SERVICES_DATA = [
  {
    "id": 1,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "MJC",
    "address": "25 Rue du Stade",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Maison Des Jeunes Et De La Culture (Mjc)",
    "lat": 45.289911,
    "lng": 4.16539
  },
  {
    "id": 2,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "Echap'toi",
    "address": "11 Rue Jules Ferry",
    "cp_ville": "43120 La Chapelle-Saint-Jean",
    "manager": "Association L'Echap'Toi",
    "lat": 45.333997,
    "lng": 4.21165
  },
  {
    "id": 3,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "Oxygène",
    "address": "Rue du Stade",
    "cp_ville": "43600 Les Tilleuls",
    "manager": "Association Oxygene",
    "lat": 45.237879,
    "lng": 4.178602
  },
  {
    "id": 4,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "Les Sympas loups",
    "address": "18 rue du Pontonnet",
    "cp_ville": "43620 Saint-Paul-en-Forez",
    "manager": "Ass Familles Rurales De St Pal De Mons",
    "lat": 45.244849,
    "lng": 4.27611
  },
  {
    "id": 5,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "Planet'air",
    "address": "Pôle Enfance et Jeunesse, Avenue de Marineo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Association Familiale De Sainte-Agathe",
    "lat": 45.240724,
    "lng": 4.236013
  },
  {
    "id": 6,
    "category": "Ados",
    "service": "ALSH Périscolaire et Extrascolaire",
    "structure": "Cap Evasion",
    "address": "Vourze",
    "cp_ville": "43590 Saint-Pierre-des-Monts",
    "manager": "Cap Evasion",
    "lat": 45.256892,
    "lng": 4.109815
  },
  {
    "id": 7,
    "category": "Ados",
    "service": "Accompagnement ados",
    "structure": "Point d’Accueil Ecoute Jeunes (PAEJ)",
    "address": "Maison de Brunelles, 12 avenue Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Ass Comm Inform Jeunesse Et D'accompagnement (A C I J A)",
    "lat": 45.293314,
    "lng": 4.175301
  },
  {
    "id": 8,
    "category": "Ados",
    "service": "Accompagnement ados",
    "structure": "Point Information Jeunesse (PIJ)",
    "address": "Maison de Brunelles, 12 avenue Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Ass Comm Inform Jeunesse Et D'accompagnement (A C I J A)",
    "lat": 45.293314,
    "lng": 4.175301
  },
  {
    "id": 9,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Arc en Jeux",
    "address": "24 Rte de la Loire",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Assoc Familiale Rurale Bas En Basset",
    "lat": 45.309009,
    "lng": 4.111188
  },
  {
    "id": 10,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Echap' toi",
    "address": "11 Rue Jules Ferry",
    "cp_ville": "43120 La Chapelle-Saint-Jean",
    "manager": "Association L'Echap'Toi",
    "lat": 45.333997,
    "lng": 4.21165
  },
  {
    "id": 11,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Oxygène",
    "address": "Rue du Stade",
    "cp_ville": "43600 Les Tilleuls",
    "manager": "Association Oxygene",
    "lat": 45.237879,
    "lng": 4.178602
  },
  {
    "id": 12,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Le Beauvoir",
    "address": "6 Lot. de Cazeneuve",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Centre De Loisirs Espace Beauvoir",
    "lat": 45.293538,
    "lng": 4.177975
  },
  {
    "id": 13,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Les têtes en l'air",
    "address": "8 Rue de l'Étang",
    "cp_ville": "43500 Chalencon-les-Pins",
    "manager": "Les Tetes En L'Air",
    "lat": 45.357719,
    "lng": 3.957342
  },
  {
    "id": 14,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "Planet'air",
    "address": "Pôle Enfance et Jeunesse, Avenue de Marineo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Association Familiale De Sainte-Agathe",
    "lat": 45.240724,
    "lng": 4.236013
  },
  {
    "id": 15,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Matin midi soir",
    "structure": "La Magie du Jeu",
    "address": "6 Av. du Stade",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Centre De Loisirs La Magie Du Jeu",
    "lat": 45.239777,
    "lng": 4.233134
  },
  {
    "id": 16,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Arc en Jeux",
    "address": "24 Rte de la Loire",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Assoc Familiale Rurale Bas En Basset",
    "lat": 45.309009,
    "lng": 4.111188
  },
  {
    "id": 17,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Cap Evasion",
    "address": "Vourze",
    "cp_ville": "43590 Saint-Pierre-des-Monts",
    "manager": "Cap Evasion",
    "lat": 45.256892,
    "lng": 4.109815
  },
  {
    "id": 18,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Echap' toi",
    "address": "11 Rue Jules Ferry",
    "cp_ville": "43120 La Chapelle-Saint-Jean",
    "manager": "Association L'Echap'Toi",
    "lat": 45.333997,
    "lng": 4.21165
  },
  {
    "id": 19,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Oxygène",
    "address": "Rue du Stade",
    "cp_ville": "43600 Les Tilleuls",
    "manager": "Association Oxygene",
    "lat": 45.237879,
    "lng": 4.178602
  },
  {
    "id": 20,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Le Beauvoir",
    "address": "6 Lot. de Cazeneuve",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Centre De Loisirs Espace Beauvoir",
    "lat": 45.293538,
    "lng": 4.177975
  },
  {
    "id": 22,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Les têtes en l'air",
    "address": "8 Rue de l'Étang",
    "cp_ville": "43500 Chalencon-les-Pins",
    "manager": "Les Tetes En L'Air",
    "lat": 45.357719,
    "lng": 3.957342
  },
  {
    "id": 23,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Les Sympas loups",
    "address": "18 rue du Pontonnet",
    "cp_ville": "43620 Saint-Paul-en-Forez",
    "manager": "Ass Familles Rurales De St Pal De Mons",
    "lat": 45.244849,
    "lng": 4.27611
  },
  {
    "id": 24,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "Planet'air",
    "address": "Pôle Enfance et Jeunesse, Avenue de Marineo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Association Familiale De Sainte-Agathe",
    "lat": 45.240724,
    "lng": 4.236013
  },
  {
    "id": 25,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Périscolaire : Mercredi",
    "structure": "La Magie du Jeu",
    "address": "6 Av. du Stade",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Centre De Loisirs La Magie Du Jeu",
    "lat": 45.239777,
    "lng": 4.233134
  },
  {
    "id": 27,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Arc en Jeux",
    "address": "24 Rte de la Loire",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Assoc Familiale Rurale Bas En Basset",
    "lat": 45.309009,
    "lng": 4.111188
  },
  {
    "id": 28,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Cap Evasion",
    "address": "Vourze",
    "cp_ville": "43590 Saint-Pierre-des-Monts",
    "manager": "Cap Evasion",
    "lat": 45.256892,
    "lng": 4.109815
  },
  {
    "id": 29,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Echap' toi",
    "address": "11 Rue Jules Ferry",
    "cp_ville": "43120 La Chapelle-Saint-Jean",
    "manager": "Association L'Echap'Toi",
    "lat": 45.333997,
    "lng": 4.21165
  },
  {
    "id": 30,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Oxygène",
    "address": "Rue du Stade",
    "cp_ville": "43600 Les Tilleuls",
    "manager": "Association Oxygene",
    "lat": 45.237879,
    "lng": 4.178602
  },
  {
    "id": 31,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Le Beauvoir",
    "address": "6 Lot. de Cazeneuve",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Centre De Loisirs Espace Beauvoir",
    "lat": 45.293538,
    "lng": 4.177975
  },
  {
    "id": 32,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Club Jeunesse",
    "address": "26 Av. Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Association Familles Rurales",
    "lat": 45.291769,
    "lng": 4.181707
  },
  {
    "id": 33,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Les têtes en l'air",
    "address": "8 Rue de l'Étang",
    "cp_ville": "43500 Chalencon-les-Pins",
    "manager": "Les Tetes En L'Air",
    "lat": 45.357719,
    "lng": 3.957342
  },
  {
    "id": 34,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Les Sympas loups",
    "address": "18 rue du Pontonnet",
    "cp_ville": "43620 Saint-Paul-en-Forez",
    "manager": "Ass Familles Rurales De St Pal De Mons",
    "lat": 45.244849,
    "lng": 4.27611
  },
  {
    "id": 35,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "Planet'air",
    "address": "Pôle Enfance et Jeunesse, Avenue de Marineo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Association Familiale De Sainte-Agathe",
    "lat": 45.240724,
    "lng": 4.236013
  },
  {
    "id": 36,
    "category": "Enfance (2-11 ans)",
    "service": "ALSH Extrascolaire",
    "structure": "La Magie du Jeu",
    "address": "6 Av. du Stade",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Centre De Loisirs La Magie Du Jeu",
    "lat": 45.239777,
    "lng": 4.233134
  },
  {
    "id": 38,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Relais Petite Enfance (RPE)",
    "structure": "La Farandole",
    "address": "24 Rte de la Loire",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Assoc Familiale Rurale Bas En Basset",
    "lat": 45.309009,
    "lng": 4.111188
  },
  {
    "id": 39,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Relais Petite Enfance (RPE)",
    "structure": "Les 6 loupiots en Marches",
    "address": "14 Av. Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "6 Loupiots En Marche",
    "lat": 45.292944,
    "lng": 4.175987
  },
  {
    "id": 40,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Ma Maison de Pouzols",
    "address": "73 Route de Pouzols",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Maison D'Assistante Maternelle Mam'Aison De Pouzols",
    "lat": 45.256723,
    "lng": 4.177911
  },
  {
    "id": 41,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Les Enfants de Gaia",
    "address": "262 Rue du Betz",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Les Enfants De Gaia",
    "lat": 45.298801,
    "lng": 4.178824
  },
  {
    "id": 42,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Des Roses et des Choux",
    "address": "Lieu dit « Lichemialle »",
    "cp_ville": "43620 SAINT-PAL-DE-MONS",
    "manager": "Maison D'Assistantes Maternelles Des Roses Et Des Choux",
    "lat": 45.260388,
    "lng": 4.269899
  },
  {
    "id": 43,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Les Louveteaux",
    "address": "6 allée des sagnes",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Les Louveteaux",
    "lat": 45.289614,
    "lng": 4.163341
  },
  {
    "id": 44,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Les Petits Barons du Marais",
    "address": "21 rue du Marais",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Mam Les P'Tits Barons Du Marais",
    "lat": 45.307304,
    "lng": 4.112731
  },
  {
    "id": 45,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Maison d'Assistantes Maternelles (MAM)",
    "structure": "Les Petits Saint Palous",
    "address": "6 place des Cânes",
    "cp_ville": "43500 Chalencon-les-Pins",
    "manager": "Les Petits Saint-Palous",
    "lat": 45.355597,
    "lng": 3.955236
  },
  {
    "id": 46,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "Au Royaume des Lutins",
    "address": "Pole Enfance Jeunesse, Vourze",
    "cp_ville": "43590 Saint-Pierre-des-Monts",
    "manager": "Au Royaume Des Lutins",
    "lat": 45.256892,
    "lng": 4.109815
  },
  {
    "id": 47,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "l'Envol",
    "address": "24 Rte de la Loire",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Familles Rurales Creche L'Envol",
    "lat": 45.309009,
    "lng": 4.111188
  },
  {
    "id": 48,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "Les Marmousets",
    "address": "14 Avenue Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Association Petite Enfance",
    "lat": 45.292944,
    "lng": 4.175987
  },
  {
    "id": 49,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "Pirouette",
    "address": "22 rue du Pontonnet",
    "cp_ville": "43620 Saint-Paul-en-Forez",
    "manager": "Creche Pirouette",
    "lat": 45.244476,
    "lng": 4.276561
  },
  {
    "id": 50,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "Toboggan",
    "address": "4 Av. de Marineo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Association Toboggan",
    "lat": 45.24069,
    "lng": 4.236118
  },
  {
    "id": 51,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "l'Echap'Mômes",
    "address": "11 Rue Jules Ferry",
    "cp_ville": "43120 La Chapelle-Saint-Jean",
    "manager": "Association L'Echap'Toi",
    "lat": 45.333997,
    "lng": 4.21165
  },
  {
    "id": 52,
    "category": "Petite Enfance (0-6 ans)",
    "service": "Crèche",
    "structure": "Les P'tits Loupiots",
    "address": "Site limousin , 30 avenue de la gare",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "6 Loupiots En Marche",
    "lat": 45.288331,
    "lng": 4.163717
  },
  {
    "id": 53,
    "category": "Solidarités",
    "service": "Aire d'accueil des gens du voyage",
    "structure": "L'HACIENDA",
    "address": "La croix St martin",
    "cp_ville": "43120 Monistrol Sur Loire",
    "manager": "Societe De Gestion Des Aires D'Accueil (Sg2A)",
    "lat": 45.270331,
    "lng": 4.196768
  },
  {
    "id": 54,
    "category": "Solidarités",
    "service": "maison france services itinérantes et conseiller numérique",
    "structure": "MFS Saint-Pierre-des-Monts",
    "address": "dans toutes les communes une fois par mois.",
    "cp_ville": "dans toutes les communes une fois par mois.",
    "manager": "Commune De Saint-Pierre-des-Monts",
    "lat": 45.2593451,
    "lng": 4.0992665
  },
  {
    "id": 55,
    "category": "Solidarités",
    "service": "Pause des aidants",
    "structure": "Ccas de Monistrol Sur Loire et Sainte-Agathe",
    "address": "MJC 25 rue du stade",
    "cp_ville": "43120 Monistrol Sur Loire",
    "manager": "Centre Communal D'Action Sociale (Ccas)",
    "lat": 45.289911,
    "lng": 4.16539
  },
  {
    "id": 56,
    "category": "Solidarités",
    "service": "Permanences France Renov",
    "structure": "CCMVR",
    "address": "ZA la Borie 1 - 9, rue de l’Épée",
    "cp_ville": "43120 Monistrol Sur Loire",
    "manager": "Communaute De Communes Marches Du Velay-Rochebaron",
    "lat": 45.281902,
    "lng": 4.18196
  },
  {
    "id": 57,
    "category": "Solidarités",
    "service": "Permanences France Renov",
    "structure": "Maison France Services",
    "address": "Rue Maréchal Foch",
    "cp_ville": "43590 Saint-Pierre-des-Monts",
    "manager": "Communaute De Communes Marches Du Velay-Rochebaron",
    "lat": 45.258775,
    "lng": 4.09938
  },
  {
    "id": 58,
    "category": "Solidarités",
    "service": "Permanences justice et partage",
    "structure": "Justice et partage",
    "address": "MJC 25 rue du stade",
    "cp_ville": "43120 Monistrol Sur Loire",
    "manager": "Justice Et Partage",
    "lat": 45.289911,
    "lng": 4.16539
  },
  {
    "id": 59,
    "category": "Solidarités",
    "service": "permanences Planning Familial",
    "structure": "Planning Familial",
    "address": "Maison de Brunelles, 12 avenue Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Mouvement Francais Pour Le Planning Familial - Association Departementale De Haute-Loire - (Planning Familial 43)",
    "lat": 45.293314,
    "lng": 4.175301
  },
  {
    "id": 60,
    "category": "Solidarités",
    "service": "Contrat Local d'Accompagnement à la Scolarité (CLAS)",
    "structure": "CLAS Monistrol",
    "address": "Ecole Lucie Aubrac",
    "cp_ville": "Place du Prévescal, 43220 Saint-Julien-sur-Loire",
    "manager": "Ass Comm Inform Jeunesse Et D'accompagnement (A C I J A)",
    "lat": 45.2941412,
    "lng": 4.1723752
  },
  {
    "id": 61,
    "category": "Solidarités",
    "service": "Contrat Local d'Accompagnement à la Scolarité (CLAS)",
    "structure": "Clas Sainte Sigolène",
    "address": "Maison du Cuerq - quartier Robin",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Ass Comm Inform Jeunesse Et D'accompagnement (A C I J A)",
    "lat": 45.240451,
    "lng": 4.234834
  },
  {
    "id": 62,
    "category": "Solidarités",
    "service": "Permanences Missions Locales",
    "structure": "Permanences Missions Locales",
    "address": "Maison de Brunelles, 12 avenue Charles de Gaulle",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Missions Locales",
    "lat": 45.293314,
    "lng": 4.175301
  },
  {
    "id": 63,
    "category": "Solidarités",
    "service": "Ludothèque",
    "structure": "Ricochet",
    "address": "14 avenue Marinéo",
    "cp_ville": "43600 Sainte-Agathe",
    "manager": "Ludothèque Ricochet",
    "lat": 45.24069,
    "lng": 4.236118
  },
  {
    "id": 64,
    "category": "Solidarités",
    "service": "RELAIS Décrochage Scolaire",
    "structure": "RELAIS Décrochage Scolaire Collège Le Monteil",
    "address": "Le Monteil, Rue Henri Pourrat",
    "cp_ville": "43120 Saint-Julien-sur-Loire",
    "manager": "Education Nationale",
    "lat": 45.291455,
    "lng": 4.161855
  },
  {
    "id": 65,
    "category": "Solidarités",
    "service": "Intervenants Sociaux en Commissariat et Gendarmerie (ISCG)",
    "structure": "Gendarmerie de Bas Monistrol",
    "address": "1 Route des Cheminots",
    "cp_ville": "43210 Mireval-sur-Loire",
    "manager": "Gendarmerie nationale",
    "lat": 45.2944,
    "lng": 4.1409
  }
];
