const SERVICES_DATA = [
    {
        "id": 1,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°1",
        "address": "Avenue du Stade",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°1",
        "lat": 45.289911,
        "lng": 4.16539
    },
    {
        "id": 2,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°2",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°2",
        "lat": 45.333997,
        "lng": 4.21165
    },
    {
        "id": 3,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°3",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°3",
        "lat": 45.237879,
        "lng": 4.178602
    },
    {
        "id": 4,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°4",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°4",
        "lat": 45.244849,
        "lng": 4.27611
    },
    {
        "id": 5,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°5",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°5",
        "lat": 45.240724,
        "lng": 4.236013
    },
    {
        "id": 6,
        "category": "Ados",
        "service": "ALSH Périscolaire et Extrascolaire",
        "structure": "Structure Publique N°6",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°6",
        "lat": 45.256892,
        "lng": 4.109815
    },
    {
        "id": 7,
        "category": "Ados",
        "service": "Accompagnement ados",
        "structure": "Structure Publique N°7",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°7",
        "lat": 45.293314,
        "lng": 4.175301
    },
    {
        "id": 8,
        "category": "Ados",
        "service": "Accompagnement ados",
        "structure": "Structure Publique N°8",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°8",
        "lat": 45.293314,
        "lng": 4.175301
    },
    {
        "id": 9,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°9",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°9",
        "lat": 45.309009,
        "lng": 4.111188
    },
    {
        "id": 10,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°10",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°10",
        "lat": 45.333997,
        "lng": 4.21165
    },
    {
        "id": 11,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°3",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°11",
        "lat": 45.237879,
        "lng": 4.178602
    },
    {
        "id": 12,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°11",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°12",
        "lat": 45.293538,
        "lng": 4.177975
    },
    {
        "id": 13,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°12",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°13",
        "lat": 45.357719,
        "lng": 3.957342
    },
    {
        "id": 14,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°5",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°14",
        "lat": 45.240724,
        "lng": 4.236013
    },
    {
        "id": 15,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Matin midi soir",
        "structure": "Structure Publique N°13",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°15",
        "lat": 45.239777,
        "lng": 4.233134
    },
    {
        "id": 16,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°9",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°16",
        "lat": 45.309009,
        "lng": 4.111188
    },
    {
        "id": 17,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°6",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°17",
        "lat": 45.256892,
        "lng": 4.109815
    },
    {
        "id": 18,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°10",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°18",
        "lat": 45.333997,
        "lng": 4.21165
    },
    {
        "id": 19,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°3",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°19",
        "lat": 45.237879,
        "lng": 4.178602
    },
    {
        "id": 20,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°11",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°20",
        "lat": 45.293538,
        "lng": 4.177975
    },
    {
        "id": 22,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°12",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°21",
        "lat": 45.357719,
        "lng": 3.957342
    },
    {
        "id": 23,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°4",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°22",
        "lat": 45.244849,
        "lng": 4.27611
    },
    {
        "id": 24,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°5",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°23",
        "lat": 45.240724,
        "lng": 4.236013
    },
    {
        "id": 25,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Périscolaire : Mercredi",
        "structure": "Structure Publique N°13",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°24",
        "lat": 45.239777,
        "lng": 4.233134
    },
    {
        "id": 27,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°9",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°25",
        "lat": 45.309009,
        "lng": 4.111188
    },
    {
        "id": 28,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°6",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°26",
        "lat": 45.256892,
        "lng": 4.109815
    },
    {
        "id": 29,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°10",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°27",
        "lat": 45.333997,
        "lng": 4.21165
    },
    {
        "id": 30,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°3",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°28",
        "lat": 45.237879,
        "lng": 4.178602
    },
    {
        "id": 31,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°11",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°29",
        "lat": 45.293538,
        "lng": 4.177975
    },
    {
        "id": 32,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°14",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°30",
        "lat": 45.291769,
        "lng": 4.181707
    },
    {
        "id": 33,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°12",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°31",
        "lat": 45.357719,
        "lng": 3.957342
    },
    {
        "id": 34,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°4",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°32",
        "lat": 45.244849,
        "lng": 4.27611
    },
    {
        "id": 35,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°5",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°33",
        "lat": 45.240724,
        "lng": 4.236013
    },
    {
        "id": 36,
        "category": "Enfance (2-11 ans)",
        "service": "ALSH Extrascolaire",
        "structure": "Structure Publique N°13",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°34",
        "lat": 45.239777,
        "lng": 4.233134
    },
    {
        "id": 38,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Relais Petite Enfance (RPE)",
        "structure": "Structure Publique N°15",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°35",
        "lat": 45.309009,
        "lng": 4.111188
    },
    {
        "id": 39,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Relais Petite Enfance (RPE)",
        "structure": "Structure Publique N°16",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°36",
        "lat": 45.292944,
        "lng": 4.175987
    },
    {
        "id": 40,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°17",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°37",
        "lat": 45.256723,
        "lng": 4.177911
    },
    {
        "id": 41,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°18",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°38",
        "lat": 45.298801,
        "lng": 4.178824
    },
    {
        "id": 42,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°19",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°39",
        "lat": 45.260388,
        "lng": 4.269899
    },
    {
        "id": 43,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°20",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°40",
        "lat": 45.289614,
        "lng": 4.163341
    },
    {
        "id": 44,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°21",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°41",
        "lat": 45.307304,
        "lng": 4.112731
    },
    {
        "id": 45,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Maison d'Assistantes Maternelles (MAM)",
        "structure": "Structure Publique N°22",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°42",
        "lat": 45.355597,
        "lng": 3.955236
    },
    {
        "id": 46,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°23",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°43",
        "lat": 45.256892,
        "lng": 4.109815
    },
    {
        "id": 47,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°24",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°44",
        "lat": 45.309009,
        "lng": 4.111188
    },
    {
        "id": 48,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°25",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°45",
        "lat": 45.292944,
        "lng": 4.175987
    },
    {
        "id": 49,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°26",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°46",
        "lat": 45.244476,
        "lng": 4.276561
    },
    {
        "id": 50,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°27",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°47",
        "lat": 45.24069,
        "lng": 4.236118
    },
    {
        "id": 51,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°28",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°48",
        "lat": 45.333997,
        "lng": 4.21165
    },
    {
        "id": 52,
        "category": "Petite Enfance (0-6 ans)",
        "service": "Crèche",
        "structure": "Structure Publique N°29",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°49",
        "lat": 45.288331,
        "lng": 4.163717
    },
    {
        "id": 53,
        "category": "Solidarités",
        "service": "Aire d'accueil des gens du voyage",
        "structure": "Structure Publique N°30",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°50",
        "lat": 45.270331,
        "lng": 4.196768
    },
    {
        "id": 54,
        "category": "Solidarités",
        "service": "maison france services itinérantes et conseiller numérique",
        "structure": "Structure Publique N°31",
        "address": "Route de la Plaine",
        "cp_ville": "dans toutes les communes une fois par mois.",
        "manager": "Gestionnaire Communal N°51",
        "lat": 45.2593451,
        "lng": 4.0992665
    },
    {
        "id": 55,
        "category": "Solidarités",
        "service": "Pause des aidants",
        "structure": "Structure Publique N°32",
        "address": "Avenue du Stade",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°52",
        "lat": 45.289911,
        "lng": 4.16539
    },
    {
        "id": 56,
        "category": "Solidarités",
        "service": "Permanences France Renov",
        "structure": "Structure Publique N°33",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°53",
        "lat": 45.281902,
        "lng": 4.18196
    },
    {
        "id": 57,
        "category": "Solidarités",
        "service": "Permanences France Renov",
        "structure": "Structure Publique N°34",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°54",
        "lat": 45.258775,
        "lng": 4.09938
    },
    {
        "id": 58,
        "category": "Solidarités",
        "service": "Permanences justice et partage",
        "structure": "Structure Publique N°35",
        "address": "Avenue du Stade",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°55",
        "lat": 45.289911,
        "lng": 4.16539
    },
    {
        "id": 59,
        "category": "Solidarités",
        "service": "permanences Planning Familial",
        "structure": "Structure Publique N°36",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°56",
        "lat": 45.293314,
        "lng": 4.175301
    },
    {
        "id": 60,
        "category": "Solidarités",
        "service": "Contrat Local d'Accompagnement à la Scolarité (CLAS)",
        "structure": "Structure Publique N°37",
        "address": "Route de la Plaine",
        "cp_ville": "Place du Prévescal, 43220 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°57",
        "lat": 45.2941412,
        "lng": 4.1723752
    },
    {
        "id": 61,
        "category": "Solidarités",
        "service": "Contrat Local d'Accompagnement à la Scolarité (CLAS)",
        "structure": "Structure Publique N°38",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°58",
        "lat": 45.240451,
        "lng": 4.234834
    },
    {
        "id": 62,
        "category": "Solidarités",
        "service": "Permanences Missions Locales",
        "structure": "Structure Publique N°39",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°59",
        "lat": 45.293314,
        "lng": 4.175301
    },
    {
        "id": 63,
        "category": "Solidarités",
        "service": "Ludothèque",
        "structure": "Structure Publique N°40",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°60",
        "lat": 45.24069,
        "lng": 4.236118
    },
    {
        "id": 64,
        "category": "Solidarités",
        "service": "RELAIS Décrochage Scolaire",
        "structure": "Structure Publique N°41",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°61",
        "lat": 45.291455,
        "lng": 4.161855
    },
    {
        "id": 65,
        "category": "Solidarités",
        "service": "Intervenants Sociaux en Commissariat et Gendarmerie (ISCG)",
        "structure": "Structure Publique N°42",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°62",
        "lat": 45.2944,
        "lng": 4.1409
    },
    {
        "id": 100,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°43",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°63",
        "lat": 45.2941412,
        "lng": 4.1723752
    },
    {
        "id": 101,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°44",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°64",
        "lat": 45.2934,
        "lng": 4.16809
    },
    {
        "id": 102,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°45",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°65",
        "lat": 45.2421,
        "lng": 4.2382
    },
    {
        "id": 103,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°46",
        "address": "Avenue du Stade",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°66",
        "lat": 45.2402,
        "lng": 4.2325
    },
    {
        "id": 104,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°47",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°67",
        "lat": 45.3065,
        "lng": 4.1135
    },
    {
        "id": 105,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°46",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Mireval-sur-Loire",
        "manager": "Gestionnaire Communal N°68",
        "lat": 45.3075,
        "lng": 4.1085
    },
    {
        "id": 106,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°48",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°69",
        "lat": 45.2595,
        "lng": 4.0985
    },
    {
        "id": 107,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°46",
        "address": "Route de la Plaine",
        "cp_ville": "43590 Saint-Pierre-des-Monts",
        "manager": "Gestionnaire Communal N°70",
        "lat": 45.2575,
        "lng": 4.0995
    },
    {
        "id": 108,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°49",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°71",
        "lat": 45.2435,
        "lng": 4.273
    },
    {
        "id": 109,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°46",
        "address": "Route de la Plaine",
        "cp_ville": "43620 Saint-Paul-en-Forez",
        "manager": "Gestionnaire Communal N°72",
        "lat": 45.2452,
        "lng": 4.2775
    },
    {
        "id": 110,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°50",
        "address": "Route de la Plaine",
        "cp_ville": "43120 La Chapelle-Saint-Jean",
        "manager": "Gestionnaire Communal N°73",
        "lat": 45.3341,
        "lng": 4.2115
    },
    {
        "id": 111,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°49",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°74",
        "lat": 45.2379,
        "lng": 4.1785
    },
    {
        "id": 112,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°51",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Les Tilleuls",
        "manager": "Gestionnaire Communal N°75",
        "lat": 45.2359,
        "lng": 4.1802
    },
    {
        "id": 113,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°52",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°76",
        "lat": 45.3582,
        "lng": 3.9568
    },
    {
        "id": 114,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°53",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Chalencon-les-Pins",
        "manager": "Gestionnaire Communal N°77",
        "lat": 45.357,
        "lng": 3.958
    },
    {
        "id": 115,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°54",
        "address": "Route de la Plaine",
        "cp_ville": "43500 Boisset-le-Vert-le-Vert",
        "manager": "Gestionnaire Communal N°78",
        "lat": 45.3242,
        "lng": 3.9825
    },
    {
        "id": 116,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°54",
        "address": "Route de la Plaine",
        "cp_ville": "43130 Saint-Andre-les-Châteaux",
        "manager": "Gestionnaire Communal N°79",
        "lat": 45.2831,
        "lng": 3.9812
    },
    {
        "id": 117,
        "category": "Écoles",
        "service": "École Privée",
        "structure": "Structure Publique N°55",
        "address": "Route de la Plaine",
        "cp_ville": "43530 Mont-Mont-Tiranges",
        "manager": "Gestionnaire Communal N°80",
        "lat": 45.303125,
        "lng": 3.98788
    },
    {
        "id": 118,
        "category": "Écoles",
        "service": "École Publique",
        "structure": "Structure Publique N°54",
        "address": "Route de la Plaine",
        "cp_ville": "43210 Valprivas",
        "manager": "Gestionnaire Communal N°81",
        "lat": 45.3115,
        "lng": 4.0458
    },
    {
        "id": 119,
        "category": "Collèges",
        "service": "Collège Public",
        "structure": "Structure Publique N°56",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°82",
        "lat": 45.291455,
        "lng": 4.161855
    },
    {
        "id": 120,
        "category": "Collèges",
        "service": "Collège Privé",
        "structure": "Structure Publique N°57",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°83",
        "lat": 45.2934,
        "lng": 4.1681
    },
    {
        "id": 121,
        "category": "Collèges",
        "service": "Collège Privé",
        "structure": "Structure Publique N°58",
        "address": "Route de la Plaine",
        "cp_ville": "43600 Sainte-Agathe",
        "manager": "Gestionnaire Communal N°84",
        "lat": 45.2425,
        "lng": 4.2345
    },
    {
        "id": 122,
        "category": "Lycées",
        "service": "Lycée Public",
        "structure": "Structure Publique N°59",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°85",
        "lat": 45.295,
        "lng": 4.178
    },
    {
        "id": 123,
        "category": "Lycées",
        "service": "Lycée Privé",
        "structure": "Structure Publique N°60",
        "address": "Route de la Plaine",
        "cp_ville": "43120 Saint-Julien-sur-Loire",
        "manager": "Gestionnaire Communal N°86",
        "lat": 45.2922,
        "lng": 4.18535
    }
];